[package]
name = "voxely"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.10"
wgpu = "23.0.1"
winit = { version = "0.29", features = ["rwh_05"] }
nalgebra = "0.33.2"
cgmath = "0.18.0"
bytemuck = "1.20.0"
futures = "0.3.31"
